[package]
name = "day_12"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clap.workspace = true
image.workspace = true
rayon.workspace = true
indicatif.workspace = true